# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-AuthZLDAP
version:      0.01
version_from: lib/Apache2/AuthZLDAP.pm
installdirs:  site
requires:
    mod_perl2:                     0
    Net::LDAPS:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
